import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
# import seaborn as sns
import numpy as np
# from autoviz.AutoViz_Class import AutoViz_Class
from scipy import stats  ## for KS test
from prettytable import PrettyTable
from PIL import Image
import time
import plotly.express as px
import streamlit as st
combined_data = pd.read_csv('Combined_data-Part_3.csv')


image = Image.open('Picture1.png')
st.sidebar.image(image, width=280)
st.sidebar.title('Marketing Analytics Project')
st.subheader('Group 3')
st.write('Chandan Malla, Niranjan, Sheshachandra, Ghulam, Prajwal')

selectbox = st.selectbox('Which section you want to go to?', ['1. Introduction', 'EDA'])
if selectbox=='1. Introduction':
    st.subheader('1. How did we select E-commerce platform for Marketing Strategy Assignment')
    st.write('Two criteria was set on which every E-commerce platform was analyzed')
    st.write('1. Ease of sharing Data by end user')
    st.write('2. Number of Users Available')
    st.write('3. Richness of Data available for analysis')
    st.write('Based on the the criteria and after having hours of discussion with the class, we settled on using data from consumers who shop from Flipkart')
    st.subheader('2. Evaluation of type of data to be analyzed')
    st.write('**A. We analyzed the invoice generated by Flipkart and from those invoices we found following data points were useful in analysis:**')
    st.write('1. Invoice ID')
    st.write('2. Order Date')
    st.write('3. MRP')
    st.write('4. Name of Product')
    st.write('5. Discount')
    st.write('6. GST')
    st.write('7. Delivery Fee')
    st.write('8. State')
    st.write('9. City')
    st.write('10. Pin')
    st.write('11. Quantity')
    st.write('**B. We also captured psychometric and demographic data from consumer whom we gathered purchase data**')
    st.write('https://docs.google.com/forms/d/1Ncinn_BE_vdlrOuikhdkX3zsHPj1ZdRzG_3DIn0PtzI/edit')
    st.subheader('3. Sources through which data was selected')
    st.subheader('4. Steps to share data for end user')


if selectbox=='cats':
    color = st.selectbox("Select a Color:", [None,'Covid', 'City_Tier', 'Sale', 'WEEKDAY','Time_Month'])
    facet_row = st.selectbox("Select a facet_row:", [None,'Covid', 'City_Tier', 'Sale', 'WEEKDAY','Time_Month'])
    facet_col = st.selectbox("Select a facet_col:", [None,'Covid', 'City_Tier', 'Sale', 'WEEKDAY','Time_Month'])

    fig = px.histogram(data_frame=combined_data, y=None, x='Log_Final Price', color=color,
    facet_row=facet_row, facet_col=facet_col,marginal='box',width=800, height=700 )
    fig.update_layout(barmode = 'overlay')
    fig.update_traces(opacity=0.70)
    fig.update_layout(
     autosize=True,
     #margin=dict(l=0, r=50, t=5, b=4  ),
    )
    st.header("Distribution of Log_Final Price")
    st.plotly_chart(fig)




